### ISSUE TITLE
Question about the CLIP Demo

### ISSUE THREAD

**Issue by g-luo** [hila-chefer/Transformer-MM-Explainability#1]
Thank you for creating this great repository! I had a few questions specifically about the CLIP demo, 

- is the attention map visualization based on the method mentioned in your paper `Generic Attention-model Explainability for Interpreting Bi-Modal and Encoder-Decoder Transformers`? I was a little confused on why the maps look different from the ones for LXMERT / DETR and why there isn't a visualization for text token attention. 
- how would you suggest visualizing the attention for the CLIP ResNet backbone?

Thanks!

**Comment by hila-chefer** [comment]
Hi @g-luo, thanks for your interest in our work!
* yes it is the same method. The difference stems from the different input to each model. ViT takes an image as input and each token is an image patch, therefore the output is a heatmap on the different patches. On the other hand, LXMERT takes as input bounding boxes and not image patches, so the output is the importance of each box, therefore we chose to present it in black and white shades and you can see that the important regions are actually bounding boxes.
As for the text- I didn’t implement the text explainability, but I’ll be sure to do that to add textual explanations to CLIP as well for completeness.
* For CLIP with ResNet I’d suggest using a CNN explainability method. The easiest is GradCAM I think, which should also be class specific.

I hope this helps.

**Comment by g-luo** [comment]
Thanks so much for the clarifications @hila-chefer!
