### ISSUE TITLE
Question about the visualization of CLIP‘s text token

### ISSUE THREAD

**Issue by Kihensarn** [hila-chefer/Transformer-MM-Explainability#18]
An excellent work. And I notice you just provided a explame to visualize the image token in CLIP's image encoder. Is it able to visualize the text token in CLIP? If it is ok, how can I do this?

**Comment by hila-chefer** [comment]
Hi @Kihensarn, thanks for your interest!

Yes! I've added textual visualization to our notebook, feel free to check it out and experiment with it!

Best,
Hila.

**Comment by Kihensarn** [comment]
Thanks，I will try it later！
