### ISSUE TITLE
Object detection/Segmentation  Explainability

### ISSUE THREAD

**Issue by jaiswati** [hila-chefer/Transformer-MM-Explainability#19]
Hello @hila-chefer,

How to get the relevance maps with Swin Transformer for Object detection/Segmentation using this technique?

Best,
@jaiswati

**Comment by hila-chefer** [comment]
Hi @jaiswati, thanks for your interest!

Our method does not support hierarchical models such as Swin out of the box. It would require some non-trivial modifications, that we have not yet attempted. I’ll update this issue if we adapt our method to Swin as well.

Best,
Hila.
