### ISSUE TITLE
Problems with running it in Google colab

### ISSUE THREAD

**Issue by songhuadan** [hila-chefer/Transformer-MM-Explainability#21]
The firt cell went through, however with the following error message:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
xarray-einstats 0.2.2 requires numpy>=1.21, but you have numpy 1.19.2 which is incompatible.
torchtext 0.13.0 requires torch==1.12.0, but you have torch 1.7.0 which is incompatible.
torchaudio 0.12.0+cu113 requires torch==1.12.0, but you have torch 1.7.0 which is incompatible.
tensorflow 2.8.2+zzzcolab20220527125636 requires numpy>=1.20, but you have numpy 1.19.2 which is incompatible.
pymc3 3.11.5 requires scipy<1.8.0,>=1.7.3, but you have scipy 1.5.2 which is incompatible.
fastai 2.7.6 requires torchvision>=0.8.2, but you have torchvision 0.8.1 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.

Then it stopped in the second cell. First with `from lxmert.lxmert.src.modeling_frcnn import GeneralizedRCNN`, I got AttributeError: module 'PIL.Image' has no attribute 'Resampling'. I `pip install Pillow==9.0.0` following [https://stackoverflow.com/questions/71738218/module-pil-has-not-attribute-resampling](url). Afterwards, I obtained AttributeError: module 'matplotlib.cbook' has no attribute '_deprecate_privatize_attribute' with `from captum.attr import visualization`. I can not find solution to get over this error. 

Most grateful if you could help.

**Comment by hila-chefer** [comment]
Hi @songhuadan, thanks for your interest!

I was able to run the LXMERT code without encountering an issue using the colab notebook, did you restart the runtime after running the first cell as instructed in the cell output?
