### ISSUE TITLE
Use non hacked models

### ISSUE THREAD

**Issue by josh-freeman** [hila-chefer/Transformer-MM-Explainability#29]
Is it possible to make it so that `attn_probs` and the other attrinbutes  necessary for explainability are present on residual attention blocks of a model coming from [here](https://github.com/openai/CLIP) or [here](https://pypi.org/project/open-clip-torch/)?

Cheerio

**Comment by hila-chefer** [comment]
Hi @josh-freeman, thanks for your interest!

Great question, sometimes you can use hooks and define those on the architecture without having to add code to save the attention maps and gradients, see [this documentation](https://pytorch.org/docs/stable/generated/torch.Tensor.register_hook.html) this would require the architecture to have some layer that outputs the attention weights, which is not the case in all architectures.
